version: "3"

services:
    db:
        container_name: database
        image: mysql:8
        restart: unless-stopped
        #platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./db/db_data:/var/lib/mysql
        networks:
            - internal

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            MYSQL_ROOT_PASSWORD: root
            ADMINER_DESIGN: hydra
        networks:
            - internal

networks:
    internal:
        external: false
